from __future__ import annotations

SPECIMEN_TYPE_MAP = {
    "punch": "Punch Biopsy",
    "core needle biopsy": "Needle Biopsy",
    "needle core biopsy": "Needle Biopsy",
    "core biopsy": "Needle Biopsy",
    "fine needle aspiration": "Fine Needle Aspiration",
    "wide local excision": "Wide Excision",
    "polypectomy": "Polypectomy",
    "appendectomy": "Excision (Total)",
    "cholecystectomy": "Excision (Total)",
    "hysterectomy": "Resection (Total)",
    "total mastectomy": "Resection (Total)",
    "biopsy": "Biopsy",
    "needle": "Needle Biopsy",
    "excision": "Excision",
    "resection": "Resection",
    "aspiration": "Fine Needle Aspiration",
}

ORGAN_KEYWORDS = {
    "adrenal": "Adrenal",
    "anus": "Anus",
    "appendix": "Appendix",
    "bile duct": "Bile Duct",
    "bladder": "Bladder",
    "bone": "Bone",
    "breast": "Breast",
    "brain": "Brain",
    "central nervous system": "Central Nervous System",
    "cervix": "Cervix",
    "colon": "Colon",
    "cutaneous": "Skin",
    "duodenum": "Duodenum",
    "endometrium": "Endometrium",
    "esophagus": "Esophagus",
    "eye": "Eye",
    "gallbladder": "Gallbladder",
    "gastric": "Stomach",
    "head and neck": "Head and Neck",
    "kidney": "Kidney",
    "larynx": "Larynx",
    "liver": "Liver",
    "lung": "Lung",
    "lymph": "Lymph Node",
    "melanoma": "Skin",
    "nasopharynx": "Nasopharynx",
    "oral cavity": "Oral Cavity",
    "oropharynx": "Oropharynx",
    "ovary": "Ovary",
    "pancreas": "Pancreas",
    "penis": "Penis",
    "pharynx": "Pharynx",
    "pituitary": "Pituitary",
    "placenta": "Placenta",
    "pleura": "Pleura",
    "prostate": "Prostate",
    "rectum": "Rectum",
    "retinoblastoma": "Eye",
    "salivary": "Salivary Gland",
    "skin": "Skin",
    "small intestine": "Small Intestine",
    "soft tissue": "Soft Tissue",
    "stomach": "Stomach",
    "testis": "Testis",
    "thyroid": "Thyroid",
    "thymus": "Thymus",
    "uterus": "Uterus",
    "uveal": "Eye",
    "vagina": "Vagina",
    "vulva": "Vulva",
}

SIZE_PATTERN = (
    r"\b\d+(?:\.\d+)?\s?(?:x\s?\d+(?:\.\d+)?\s?){0,2}(?:cm|mm)\b"
)

SECTION_HEADINGS = (
    "procedure",
    "gross description",
    "specimen",
)

STOPWORDS_IN_SPECIMEN_NAME = {
    "protocol",
    "examination",
    "patients",
    "patient",
    "carcinoma",
    "tumor",
    "tumour",
    "synoptic",
    "reporting",
    "template",
    "case",
    "summary",
}
