# Generated by Django 4.2.11 on 2026-05-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0002_dedupe_specimens'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='specimen',
            new_name='pathology_s_specime_43187c_idx',
            old_name='pathology_s_specime_b2402e_idx',
        ),
        migrations.RenameIndex(
            model_name='specimen',
            new_name='pathology_s_source__82f29d_idx',
            old_name='pathology_s_source__ee0ad2_idx',
        ),
    ]
