# Generated by Django 4.2.11 on 2026-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0005_crawljob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljob',
            name='limit',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to crawl all available CAP protocol documents.', null=True),
        ),
    ]
