# Generated by Django 4.2.11 on 2026-05-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0008_crawljob_crawl_source'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='specimen',
            new_name='pathology_s_source__b4a9b5_idx',
            old_name='pathology_s_source__18d9cb_idx',
        ),
    ]
