# Generated by Django 4.2.11 on 2026-08-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0010_specimen_procedure_and_clinical_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljob',
            name='crawl_source',
            field=models.CharField(choices=[('cap.org', 'CAP'), ('pathologyoutlines.com', 'Pathology Outlines'), ('both', 'Both Sources')], default='both', max_length=64),
        ),
    ]
